### ISSUE TITLE
Make.cmd

### ISSUE THREAD

**Issue by xan2622** [OpenRA/TilesetBuilder#2]
OpenRA has a **make.cmd** file used to download dependencies and compile the source code (from command line). It's very handy for people who haven't installed Visual Studio (which takes a lot of HDD space).

It would be really interesting/useful to have such a file in the TilesetBuilder repository too.

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/TilesetBuilder/issues/3 (needs someone on Windows to test).
